# region DRAMA Using Directives
    global using DRAMA.Extensions;
    global using DRAMA.Models.TabularData;
# endregion

# region Microsoft Using Directives
    global using Microsoft.Playwright;
# endregion

# region NUnit Using Directives
    global using NUnit.Framework;
# endregion

# region System Using Directives
    global using System.Reflection;
    global using System.Text.Json;
# endregion
