# region DRAMA Using Directives
    global using DRAMA.Extensions;
# endregion

# region Microsoft Using Directives
    global using Microsoft.Playwright;
# endregion

# region NUnit Using Directives
    global using NUnit.Framework;
# endregion

# region System Using Directives
    global using System;
    global using System.Collections.Generic;
    global using System.IO;
    global using System.Linq;
    global using System.Reflection;
    global using System.Text.Json;
    global using System.Threading;
    global using System.Threading.Tasks;
# endregion
