namespace DRAMA.Enumerations;

public static class DatabaseEngine
{
    public const string MariaDB = "MariaDB";
    public const string MSAzure = "Microsoft Azure SQL Database";
    public const string MSSQLServer = "Microsoft SQL Server";
    public const string MongoDB = "MongoDB";
    public const string MySQL = "MySQL";
    public const string Oracle = "Oracle";
    public const string PostgreSQL = "PostgreSQL";
    public const string SQLite = "SQLite";
}
