@Unit
Feature: Detokeniser
	WHEN I TOKENISE DATA
	THE RETRIEVED VALUES SHOULD BE CORRECTLY DETOKENISED


	Scenario: [01/01] Tokenise And Detokenise Data
		When  I STORE THE STRING VALUE "foo" INTO ENVIRONMENT VARIABLE "STRING"
		And   I STORE THE INTEGER VALUE "1" INTO ENVIRONMENT VARIABLE "INTEGER"

		And   I STORE THE STRING VALUE "bar" WITH KEY "STRING" INTO THE TEST RUN CONTEXT
		And   I STORE THE INTEGER VALUE "2" WITH KEY "INTEGER" INTO THE TEST RUN CONTEXT

		And   I STORE THE STRING VALUE "quz" WITH KEY "STRING" INTO THE FEATURE CONTEXT
		And   I STORE THE INTEGER VALUE "3" WITH KEY "INTEGER" INTO THE FEATURE CONTEXT

		And   I STORE THE STRING VALUE "zod" WITH KEY "STRING" INTO THE SCENARIO CONTEXT
		And   I STORE THE INTEGER VALUE "4" WITH KEY "INTEGER" INTO THE SCENARIO CONTEXT

		Then  TOKENISED VALUE "[¦STRING¦]" SHOULD EQUAL DETOKENISED VALUE "foo"
		And   TOKENISED VALUE "[¦INTEGER¦]" SHOULD EQUAL DETOKENISED VALUE "1"

		And   TOKENISED VALUE "<¦STRING¦>" SHOULD EQUAL DETOKENISED VALUE "bar"
		And   TOKENISED VALUE "<¦INTEGER¦>" SHOULD EQUAL DETOKENISED VALUE "2"

		And   TOKENISED VALUE "{¦STRING¦}" SHOULD EQUAL DETOKENISED VALUE "quz"
		And   TOKENISED VALUE "{¦INTEGER¦}" SHOULD EQUAL DETOKENISED VALUE "3"

		And   TOKENISED VALUE "(¦STRING¦)" SHOULD EQUAL DETOKENISED VALUE "zod"
		And   TOKENISED VALUE "(¦INTEGER¦)" SHOULD EQUAL DETOKENISED VALUE "4"

		And   TOKENISED VALUE "zod" SHOULD EQUAL DETOKENISED VALUE "zod"
		And   TOKENISED VALUE "4" SHOULD EQUAL DETOKENISED VALUE "4"
