# region DRAMA Usings
    global using DRAMA.Extensions;
    global using DRAMA.Helpers.TabularData;
    global using DRAMA.Models.TabularData;
# endregion

# region Microsoft Usings
    global using Microsoft.Playwright;
# endregion

# region TechTalk Usings
    global using TechTalk.SpecFlow;
# endregion

# region System Usings
    global using System;
    global using System.Collections.Generic;
    global using System.Globalization;
    global using System.Linq;
    global using System.Text.Json;
    global using System.Threading;
    global using System.Threading.Tasks;
# endregion