# region AventStack Using Directives // TODO: Remove These Using Directives After Migrating Away From Extent Reports
    global using AventStack.ExtentReports;
    global using AventStack.ExtentReports.Gherkin.Model;
    global using AventStack.ExtentReports.Reporter;
    global using AventStack.ExtentReports.Reporter.Configuration;
# endregion

# region DRAMA Using Directives
    global using DRAMA.Attributes;
    global using DRAMA.Enumerations;
    global using DRAMA.Extensions.Context;
    global using DRAMA.Extensions.TargetFramework;
    global using DRAMA.Helpers.Configuration;
    global using DRAMA.Helpers.TabularData;
    global using DRAMA.Models.Configuration;
    global using DRAMA.Models.TabularData;
    global using DRAMA.Models.TargetFramework;
# endregion

# region Microsoft Using Directives
    global using Microsoft.Data.Sqlite;
    global using Microsoft.Playwright;
# endregion

# region MySQL Using Directives
    global using MySql.Data.MySqlClient;
# endregion

# region Newtonsoft Using Directives
    global using Newtonsoft.Json;
    global using Newtonsoft.Json.Linq;
    global using Newtonsoft.Json.Schema;
# endregion

# region Oracle Using Directives
    global using Oracle.ManagedDataAccess.Client;
# endregion

# region PostgreSQL Using Directives
    global using Npgsql;
# endregion

# region TechTalk Using Directives
    global using TechTalk.SpecFlow;
    global using TechTalk.SpecFlow.Bindings;
    global using TechTalk.SpecFlow.UnitTestProvider;
# endregion

# region System Using Directives
    global using System.Data;
    global using System.Data.Common;
    global using System.Data.SqlClient;
    global using System.Configuration;
    global using System.Globalization;
    global using System.Reflection;
    global using System.Runtime.Serialization;
    global using System.Text;
    global using System.Text.Json;
# endregion
