# region DRAMA Using Directives
    global using DRAMA.Extensions.TargetFramework;
    global using DRAMA.Helpers.TabularData;
    global using DRAMA.Models.TabularData;
# endregion

# region Microsoft Using Directives
    global using Microsoft.Playwright;
# endregion

# region TechTalk Using Directives
    global using TechTalk.SpecFlow;
# endregion

# region System Using Directives
    global using System.Globalization;
    global using System.Text.Json;
# endregion
