global using AventStack.ExtentReports.Gherkin.Model;

global using DRAMA.Models.SystemUnderTest;
global using DRAMA.Extensions.Specflow;
global using DRAMA.Extensions.TargetFramework;
global using DRAMA.Prototypes;

global using Microsoft.Playwright;

global using NUnit.Framework;

global using Newtonsoft.Json;

global using System;
global using System.Collections.Generic;
global using System.Data;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Threading.Tasks;

global using TechTalk.SpecFlow.Assist;
global using TechTalk.SpecFlow;

// TODO: Clean This Up
