# region DRAMA Using Directives
    global using DRAMA.Contexts;
    global using DRAMA.Extensions.Context;
    global using DRAMA.Prototypes;
# endregion

# region Microsoft Using Directives
    global using Microsoft.Playwright;
# endregion

# region NUnit Using Directives
    global using NUnit.Framework;
# endregion

# region System Using Directives
    global using System;
    global using System.Data;
    global using System.IO;
    global using System.Linq;
    global using System.Threading.Tasks;
# endregion

# region TechTalk Using Directives
    global using TechTalk.SpecFlow;
# endregion
